title: "Dandan Wei"
description: "Postdoctoral Fellow at ISTA, Austria"
url: "https://Dandan-star0.github.io"
theme: null

header_pages:
  - index.md
  - research.md
  - publications.md
  - cv.md

social_links:
  github: "https://github.com/Dandan-star0"
  scholar: "https://scholar.google.com/"
  email: "dandan.wei@ista.ac.at"


  include:
  - assets/css/style.css

